binop_separator = "Back"
condense_wildcard_suffixes = true
error_on_line_overflow = true
error_on_unformatted = true
format_strings = true
hard_tabs = true
match_block_trailing_comma = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
use_field_init_shorthand = true
use_try_shorthand = true
