language: rust
rust:
  - stable
  - beta
before_script:
  - rustup toolchain install nightly
  - rustup component add rustfmt --toolchain nightly
script:
  - cargo +nightly fmt --all -- --check
  - cargo build
  - cargo test
