language: rust

rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
  - rust: nightly

jobs:
  include:
  - stage: "Code coverage"
    rust: nightly
    os: linux
    script:
    - |
      set -e
      curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      export CARGO_INCREMENTAL=0
      export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
      cargo build --verbose
      cargo test --verbose
      zip -0 ccov.zip `find . \( -name "finality_grandpa*.gc*" \) -print`
      ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info
      bash <(curl -s https://codecov.io/bash) -f lcov.info
