[package]
name = "finality-grandpa"
version = "0.9.1"
description = "PBFT-based finality gadget for blockchains"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"
repository = "https://github.com/paritytech/finality-grandpa"
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.17"
futures-timer = "0.3.0"
log = "0.4"
parking_lot = { version = "0.9", optional = true }
parity-scale-codec = { version = "1.0.3", optional = true, default-features = false, features = ["derive"] }
num = { package = "num-traits", version = "0.2", default-features = false }
hashbrown = { version = "0.6.3", default-features = false }

[dev-dependencies]
rand = "0.6.0"

[features]
default = ["std"]
std = ["parity-scale-codec/std", "num/std", "parking_lot"]
derive-codec = ["parity-scale-codec"]
test-helpers = []
