[package]
name = "finality-grandpa"
version = "0.13.0"
description = "PBFT-based finality gadget for blockchains"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"
repository = "https://github.com/paritytech/finality-grandpa"
edition = "2018"

[dependencies]
async-trait = "0.1.36"
async-rwlock = { version = "1.3.0", optional = true }
futures = { version = "0.3.7", default-features = false, features = [ "async-await" ] }
futures-timer = { version = "2.0.2", optional = true }
log = { version = "0.4", optional = true }
parity-scale-codec = { version = "1.0.3", optional = true, default-features = false, features = ["derive"] }
num = { package = "num-traits", version = "0.2", default-features = false }
rand = {version = "0.6.0", optional = true }
either = { version = "1.5.3", default-features = false }

[dev-dependencies]
rand = "0.7.0"
quickcheck = "0.9"
parking_lot = "0.9"
async-std = { version = "1.6.5", features = ["unstable"] }
env_logger = "0.8"


[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"num/std",
	"async-rwlock",
	"log",
	"futures-timer",
	"futures/executor",
	"futures/async-await",
]
derive-codec = ["parity-scale-codec"]
test-helpers = ["fuzz-helpers", "rand", "std"]
fuzz-helpers = []
