[package]
name = "finality-afg"
version = "0.1.0"
description = "PBFT-based finality gadget for blockchains"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
parking_lot = "0.4"
log = "0.4"
futures = "0.1"

[dev-dependencies]
tokio = "0.1.8"
exit-future = "0.1.2"
