[package]
name = "finality-grandpa"
version = "0.13.0"
description = "PBFT-based finality gadget for blockchains"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"
repository = "https://github.com/paritytech/finality-grandpa"
edition = "2018"

[dependencies]
futures = { version = "0.3.5", default-features = false }
futures-timer = { version = "3.0.2", optional = true }
log = { version = "0.4", optional = true }
parking_lot = { version = "0.11", optional = true }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"], optional = true }
num = { package = "num-traits", version = "0.2", default-features = false }
rand = { version = "0.8.0", optional = true }
either = { version = "1.6.1", default-features = false }

[dev-dependencies]
rand = "0.7.0"
quickcheck = "0.9"

[features]
default = ["std"]
std = ["parity-scale-codec/std", "num/std", "parking_lot", "log", "futures-timer", "futures/executor"]
derive-codec = ["parity-scale-codec"]
test-helpers = ["fuzz-helpers", "rand", "std"]
fuzz-helpers = []
